### PR TITLE
build for focal

### PR DESCRIPTION
**Pull request by mboeder-2306**
With these changes, it runs on focal again.

### CODE REVIEW

**Comment by cibersheep** [comment]
Oh! Awesome. I forgot about this small port :)
I'll take some time to check this. Thank you <3

**Comment by mboeder-2306** [comment]
OFFTOPIC: But i just noticed that you are also the author of this repo: https://gitlab.com/cibersheep/keeweb-ubuntu-touch/-/merge_requests/2 ^^' This is a REALLY useful App for me. Do you have time to get it back in the store? I think it would be helpful for a lot of users :)

**Comment by cibersheep** [comment]
> This is a REALLY useful App for me.

I'm not the author, just wrapped around for it to work in UT ;)
I honestly think helping this app would be better: https://open-store.io/app/keepass.davidv.dev
as it is a «proper» qml app

**Comment by cibersheep** [comment]
https://github.com/cibersheep/frogger/commit/2b2ed88e6cfa02e2f04de3f17e0df7874f89dcfd

I have modified the files accordingly. I think now should show splah screen instructions... I have to reinstall clickable

**Pull request merged**
